/*===OmniBridgeOs/kernel/arch/x64/user/win32_api_table.c===*/
/*
 * Win32 API 名称表 —— 500 项。
 *
 * 人工必须审查：
 *   - 编号范围 [0x2001, 0x21F4] 共 500 项，无重复，无遗漏。
 *   - 无与 Linux syscall (0..~450) / OB syscall (0x100..0x15E) 重叠。
 *   - 表项顺序不限；查表在运行时线性扫描。
 */
#include "win32_api_table.h"

/* 使用短宏降低表体体积，避免 500 行 × 3 字段重复。 */
#define K32(name, nr)   { "kernel32", name, nr }
#define K32X(name, disp, nr) { "kernel32", disp, nr }
#define MCRT(name, nr)  { "msvcrt",   name, nr }
#define ADV(name, nr)   { "advapi32", name, nr }
#define U32(name, nr)   { "user32",   name, nr }
#define G32(name, nr)   { "gdi32",    name, nr }
#define SH32(name, nr)  { "shell32",  name, nr }
#define OLE(name, nr)   { "ole32",    name, nr }
#define WS2(name, nr)   { "ws2_32",   name, nr }
#define MM(name, nr)    { "winmm",    name, nr }
#define CC32(name, nr)  { "comctl32", name, nr }
#define NTD(name, nr)   { "ntdll",    name, nr }
#define UENV(name, nr)  { "userenv",  name, nr }

const struct win32_api_entry g_win32_api_table[] = {
    /* ---------- 原有 32 项（0x2001 .. 0x2020） ---------- */
    K32("GetStdHandle",           WIN32_API_GetStdHandle),
    K32("WriteFile",              WIN32_API_WriteFile),
    K32("ReadFile",               WIN32_API_ReadFile),
    K32("ExitProcess",            WIN32_API_ExitProcess),
    K32("GetLastError",           WIN32_API_GetLastError),
    K32("SetLastError",           WIN32_API_SetLastError),
    K32("CreateFileA",            WIN32_API_CreateFileA),
    K32("CreateFileW",            WIN32_API_CreateFileW),
    K32("CloseHandle",            WIN32_API_CloseHandle),
    K32("GetFileSize",            WIN32_API_GetFileSize),
    K32("GetFileSizeEx",          WIN32_API_GetFileSizeEx),
    K32("SetFilePointer",         WIN32_API_SetFilePointer),
    K32("SetFilePointerEx",       WIN32_API_SetFilePointerEx),
    K32("GetCurrentProcessId",    WIN32_API_GetCurrentProcessId),
    K32("GetCurrentThreadId",     WIN32_API_GetCurrentThreadId),
    K32("GetTickCount",           WIN32_API_GetTickCount),
    K32("Sleep",                  WIN32_API_Sleep),
    K32("GetCommandLineA",        WIN32_API_GetCommandLineA),
    K32("GetCommandLineW",        WIN32_API_GetCommandLineW),
    K32("GetEnvironmentStrings",  WIN32_API_GetEnvironmentStrings),
    K32("GetModuleHandleA",       WIN32_API_GetModuleHandleA),
    K32("GetModuleHandleW",       WIN32_API_GetModuleHandleW),
    K32("GetModuleFileNameA",     WIN32_API_GetModuleFileNameA),
    K32("GetModuleFileNameW",     WIN32_API_GetModuleFileNameW),
    K32("HeapAlloc",              WIN32_API_HeapAlloc),
    K32("HeapFree",               WIN32_API_HeapFree),
    K32("GetProcessHeap",         WIN32_API_GetProcessHeap),
    K32("GetStartupInfoA",        WIN32_API_GetStartupInfoA),
    K32("GetStartupInfoW",        WIN32_API_GetStartupInfoW),
    K32("VirtualAlloc",           WIN32_API_VirtualAlloc),
    K32("VirtualFree",            WIN32_API_VirtualFree),
    K32("GetVersion",             WIN32_API_GetVersion),

    /* ---------- kernel32 附加 ---------- */
    K32("SetStdHandle",            WIN32_API_SetStdHandle),
    K32("GetTickCount64",          WIN32_API_GetTickCount64),
    K32("SleepEx",                 WIN32_API_SleepEx),
    K32("TerminateProcess",        WIN32_API_TerminateProcess),
    K32("GetExitCodeProcess",      WIN32_API_GetExitCodeProcess),
    K32("GetExitCodeThread",       WIN32_API_GetExitCodeThread),
    K32("FlushFileBuffers",        WIN32_API_FlushFileBuffers),
    K32("DeleteFileA",             WIN32_API_DeleteFileA),
    K32("DeleteFileW",             WIN32_API_DeleteFileW),
    K32("MoveFileA",               WIN32_API_MoveFileA),
    K32("MoveFileW",               WIN32_API_MoveFileW),
    K32("CopyFileA",               WIN32_API_CopyFileA),
    K32("CopyFileW",               WIN32_API_CopyFileW),
    K32("GetFileAttributesA",      WIN32_API_GetFileAttributesA),
    K32("GetFileAttributesW",      WIN32_API_GetFileAttributesW),
    K32("SetFileAttributesA",      WIN32_API_SetFileAttributesA),
    K32("SetFileAttributesW",      WIN32_API_SetFileAttributesW),
    K32("FindFirstFileA",          WIN32_API_FindFirstFileA),
    K32("FindNextFileA",           WIN32_API_FindNextFileA),
    K32("FindClose",               WIN32_API_FindClose),
    K32("GetFullPathNameA",        WIN32_API_GetFullPathNameA),
    K32("GetFullPathNameW",        WIN32_API_GetFullPathNameW),
    K32("CreateDirectoryA",        WIN32_API_CreateDirectoryA),
    K32("CreateDirectoryW",        WIN32_API_CreateDirectoryW),
    K32("RemoveDirectoryA",        WIN32_API_RemoveDirectoryA),
    K32("RemoveDirectoryW",        WIN32_API_RemoveDirectoryW),
    K32("GetCurrentDirectoryA",    WIN32_API_GetCurrentDirectoryA),
    K32("GetCurrentDirectoryW",    WIN32_API_GetCurrentDirectoryW),
    K32("SetCurrentDirectoryA",    WIN32_API_SetCurrentDirectoryA),
    K32("SetCurrentDirectoryW",    WIN32_API_SetCurrentDirectoryW),
    K32("GetFileType",             WIN32_API_GetFileType),
    K32("SetEndOfFile",            WIN32_API_SetEndOfFile),
    K32("HeapCreate",              WIN32_API_HeapCreate),
    K32("HeapDestroy",             WIN32_API_HeapDestroy),
    K32("HeapReAlloc",             WIN32_API_HeapReAlloc),
    K32("HeapSize",                WIN32_API_HeapSize),
    K32("VirtualAllocEx",          WIN32_API_VirtualAllocEx),
    K32("VirtualFreeEx",           WIN32_API_VirtualFreeEx),
    K32("VirtualProtect",          WIN32_API_VirtualProtect),
    K32("VirtualQuery",            WIN32_API_VirtualQuery),
    K32("GlobalAlloc",             WIN32_API_GlobalAlloc),
    K32("GlobalFree",              WIN32_API_GlobalFree),
    K32("LocalAlloc",              WIN32_API_LocalAlloc),
    K32("LocalFree",               WIN32_API_LocalFree),
    K32("CreateProcessA",          WIN32_API_CreateProcessA),
    K32("CreateProcessW",          WIN32_API_CreateProcessW),
    K32("OpenProcess",             WIN32_API_OpenProcess),
    K32("GetCurrentProcess",       WIN32_API_GetCurrentProcess),
    K32("GetCurrentThread",        WIN32_API_GetCurrentThread),
    K32("CreateThread",            WIN32_API_CreateThread),
    K32("ExitThread",              WIN32_API_ExitThread),
    K32("WaitForSingleObject",     WIN32_API_WaitForSingleObject),
    K32("WaitForMultipleObjects",  WIN32_API_WaitForMultipleObjects),
    K32("SetEvent",                WIN32_API_SetEvent),
    K32("ResetEvent",              WIN32_API_ResetEvent),
    K32("CreateEventA",            WIN32_API_CreateEventA),
    K32("CreateEventW",            WIN32_API_CreateEventW),
    K32("CreateMutexA",            WIN32_API_CreateMutexA),
    K32("CreateMutexW",            WIN32_API_CreateMutexW),
    K32("ReleaseMutex",            WIN32_API_ReleaseMutex),
    K32("InitializeCriticalSection", WIN32_API_InitializeCriticalSection),
    K32("EnterCriticalSection",    WIN32_API_EnterCriticalSection),
    K32("LeaveCriticalSection",    WIN32_API_LeaveCriticalSection),
    K32("DeleteCriticalSection",   WIN32_API_DeleteCriticalSection),
    K32("SuspendThread",           WIN32_API_SuspendThread),
    K32("ResumeThread",            WIN32_API_ResumeThread),
    K32("GetThreadPriority",       WIN32_API_GetThreadPriority),
    K32("SetThreadPriority",       WIN32_API_SetThreadPriority),
    K32("GetVersionExA",           WIN32_API_GetVersionExA),
    K32("GetVersionExW",           WIN32_API_GetVersionExW),
    K32("GetEnvironmentVariableA", WIN32_API_GetEnvironmentVariableA),
    K32("GetEnvironmentVariableW", WIN32_API_GetEnvironmentVariableW),
    K32("SetEnvironmentVariableA", WIN32_API_SetEnvironmentVariableA),
    K32("SetEnvironmentVariableW", WIN32_API_SetEnvironmentVariableW),
    K32("GetTempPathA",            WIN32_API_GetTempPathA),
    K32("GetTempPathW",            WIN32_API_GetTempPathW),
    K32("GetTempFileNameA",        WIN32_API_GetTempFileNameA),
    K32("GetTempFileNameW",        WIN32_API_GetTempFileNameW),
    K32("GetSystemDirectoryA",     WIN32_API_GetSystemDirectoryA),
    K32("GetSystemDirectoryW",     WIN32_API_GetSystemDirectoryW),
    K32("GetWindowsDirectoryA",    WIN32_API_GetWindowsDirectoryA),
    K32("GetWindowsDirectoryW",    WIN32_API_GetWindowsDirectoryW),
    K32("GetSystemInfo",           WIN32_API_GetSystemInfo),
    K32("GetSystemTime",           WIN32_API_GetSystemTime),
    K32("GetLocalTime",            WIN32_API_GetLocalTime),
    K32("SystemTimeToFileTime",    WIN32_API_SystemTimeToFileTime),
    K32("FileTimeToSystemTime",    WIN32_API_FileTimeToSystemTime),
    K32("QueryPerformanceCounter", WIN32_API_QueryPerformanceCounter),
    K32("QueryPerformanceFrequency", WIN32_API_QueryPerformanceFrequency),
    K32("GetComputerNameA",        WIN32_API_GetComputerNameA),
    K32("GetComputerNameW",        WIN32_API_GetComputerNameW),
    K32("GetUserNameA",            WIN32_API_GetUserNameA),
    K32("GetUserNameW",            WIN32_API_GetUserNameW),
    K32("GetSystemTimeAsFileTime", WIN32_API_GetSystemTimeAsFileTime),
    K32("GetSystemTimes",          WIN32_API_GetSystemTimes),
    K32("GetProcessTimes",         WIN32_API_GetProcessTimes),
    K32("GetThreadTimes",          WIN32_API_GetThreadTimes),
    K32("GetACP",                  WIN32_API_GetACP),
    K32("GetOEMCP",                WIN32_API_GetOEMCP),
    K32("GetCPInfo",               WIN32_API_GetCPInfo),
    K32("GetConsoleCP",            WIN32_API_GetConsoleCP),
    K32("GetConsoleOutputCP",      WIN32_API_GetConsoleOutputCP),
    K32("GetConsoleMode",          WIN32_API_GetConsoleMode),
    K32("SetConsoleMode",          WIN32_API_SetConsoleMode),
    K32("GetConsoleScreenBufferInfo", WIN32_API_GetConsoleScreenBufferInfo),
    K32("SetConsoleCursorPosition", WIN32_API_SetConsoleCursorPosition),
    K32("SetConsoleTextAttribute", WIN32_API_SetConsoleTextAttribute),
    K32("WriteConsoleA",           WIN32_API_WriteConsoleA),
    K32("WriteConsoleW",           WIN32_API_WriteConsoleW),
    K32("ReadConsoleA",            WIN32_API_ReadConsoleA),
    K32("ReadConsoleW",            WIN32_API_ReadConsoleW),
    K32("AllocConsole",            WIN32_API_AllocConsole),
    K32("FreeConsole",             WIN32_API_FreeConsole),
    K32("GetConsoleWindow",        WIN32_API_GetConsoleWindow),
    K32("lstrlenA",                WIN32_API_lstrlenA),
    K32("lstrlenW",                WIN32_API_lstrlenW),
    K32("lstrcpyA",                WIN32_API_lstrcpyA),
    K32("lstrcpyW",                WIN32_API_lstrcpyW),
    K32("lstrcatA",                WIN32_API_lstrcatA),
    K32("lstrcatW",                WIN32_API_lstrcatW),
    K32("lstrcmpA",                WIN32_API_lstrcmpA),
    K32("lstrcmpW",                WIN32_API_lstrcmpW),
    K32("lstrcmpiA",               WIN32_API_lstrcmpiA),
    K32("lstrcmpiW",               WIN32_API_lstrcmpiW),
    K32("MulDiv",                  WIN32_API_MulDiv),
    K32("IsDebuggerPresent",       WIN32_API_IsDebuggerPresent),
    K32("OutputDebugStringA",      WIN32_API_OutputDebugStringA),
    K32("OutputDebugStringW",      WIN32_API_OutputDebugStringW),
    K32("DebugBreak",              WIN32_API_DebugBreak),
    K32("GetLogicalDrives",        WIN32_API_GetLogicalDrives),
    K32("GetLogicalDriveStringsA", WIN32_API_GetLogicalDriveStringsA),
    K32("GetLogicalDriveStringsW", WIN32_API_GetLogicalDriveStringsW),
    K32("GetDriveTypeA",           WIN32_API_GetDriveTypeA),
    K32("GetDriveTypeW",           WIN32_API_GetDriveTypeW),
    K32("GetVolumeInformationA",   WIN32_API_GetVolumeInformationA),
    K32("GetVolumeInformationW",   WIN32_API_GetVolumeInformationW),
    K32("GetDiskFreeSpaceA",       WIN32_API_GetDiskFreeSpaceA),
    K32("GetDiskFreeSpaceW",       WIN32_API_GetDiskFreeSpaceW),
    K32("GetFileTime",             WIN32_API_GetFileTime),
    K32("SetFileTime",             WIN32_API_SetFileTime),
    K32("GetFileInformationByHandle", WIN32_API_GetFileInformationByHandle),
    K32("LockFile",                WIN32_API_LockFile),
    K32("UnlockFile",              WIN32_API_UnlockFile),
    K32("CreatePipe",              WIN32_API_CreatePipe),
    K32("PeekNamedPipe",           WIN32_API_PeekNamedPipe),
    K32("ReadFileEx",              WIN32_API_ReadFileEx),
    K32("WriteFileEx",             WIN32_API_WriteFileEx),
    K32("GetOverlappedResult",     WIN32_API_GetOverlappedResult),
    K32("CreateIoCompletionPort",  WIN32_API_CreateIoCompletionPort),
    K32("GetQueuedCompletionStatus", WIN32_API_GetQueuedCompletionStatus),
    K32("PostQueuedCompletionStatus", WIN32_API_PostQueuedCompletionStatus),
    K32("DeviceIoControl",         WIN32_API_DeviceIoControl),
    K32("FindFirstFileExA",        WIN32_API_FindFirstFileExA),
    K32("FindFirstFileExW",        WIN32_API_FindFirstFileExW),
    K32("FindFirstChangeNotificationA", WIN32_API_FindFirstChangeNotificationA),
    K32("FindFirstChangeNotificationW", WIN32_API_FindFirstChangeNotificationW),
    K32("FindNextChangeNotification", WIN32_API_FindNextChangeNotification),
    K32("FindCloseChangeNotification", WIN32_API_FindCloseChangeNotification),
    K32("CreateDirectoryExA",     WIN32_API_CreateDirectoryExA),
    K32("CreateDirectoryExW",     WIN32_API_CreateDirectoryExW),
    K32("GetFileSecurityA",       WIN32_API_GetFileSecurityA),
    K32("GetFileSecurityW",       WIN32_API_GetFileSecurityW),
    K32("SetFileSecurityA",       WIN32_API_SetFileSecurityA),
    K32("SetFileSecurityW",       WIN32_API_SetFileSecurityW),
    K32("CompareFileTime",        WIN32_API_CompareFileTime),
    K32("GetSystemDefaultLangID", WIN32_API_GetSystemDefaultLangID),
    K32("GetUserDefaultLangID",   WIN32_API_GetUserDefaultLangID),
    K32("GetSystemDefaultLCID",   WIN32_API_GetSystemDefaultLCID),
    K32("GetUserDefaultLCID",     WIN32_API_GetUserDefaultLCID),
    K32("GetThreadLocale",        WIN32_API_GetThreadLocale),
    K32("SetThreadLocale",        WIN32_API_SetThreadLocale),
    K32("IsValidCodePage",        WIN32_API_IsValidCodePage),
    K32("GetCPInfoExA",           WIN32_API_GetCPInfoExA),
    K32("GetCPInfoExW",           WIN32_API_GetCPInfoExW),
    K32("GetNumberFormatA",       WIN32_API_GetNumberFormatA),
    K32("GetNumberFormatW",       WIN32_API_GetNumberFormatW),
    K32("GetDateFormatA",         WIN32_API_GetDateFormatA),
    K32("GetDateFormatW",         WIN32_API_GetDateFormatW),
    K32("GetTimeFormatA",         WIN32_API_GetTimeFormatA),
    K32("GetTimeFormatW",         WIN32_API_GetTimeFormatW),
    K32("MultiByteToWideChar",    WIN32_API_MultiByteToWideChar),
    K32("WideCharToMultiByte",    WIN32_API_WideCharToMultiByte),
    K32("CompareStringA",         WIN32_API_CompareStringA),
    K32("CompareStringW",         WIN32_API_CompareStringW),
    K32("LCMapStringA",           WIN32_API_LCMapStringA),
    K32("LCMapStringW",           WIN32_API_LCMapStringW),
    K32("GetStringTypeA",         WIN32_API_GetStringTypeA),
    K32("GetStringTypeW",         WIN32_API_GetStringTypeW),
    K32("CharUpperA",             WIN32_API_CharUpperA),
    K32("CharUpperW",             WIN32_API_CharUpperW),
    K32("CharLowerA",             WIN32_API_CharLowerA),
    K32("CharLowerW",             WIN32_API_CharLowerW),
    K32("GetLongPathNameA",       WIN32_API_GetLongPathNameA),
    K32("GetLongPathNameW",       WIN32_API_GetLongPathNameW),
    K32("GetShortPathNameA",      WIN32_API_GetShortPathNameA),
    K32("GetShortPathNameW",      WIN32_API_GetShortPathNameW),
    K32("CreateFileMappingA",     WIN32_API_CreateFileMappingA),
    K32("CreateFileMappingW",     WIN32_API_CreateFileMappingW),
    K32("OpenFileMappingA",       WIN32_API_OpenFileMappingA),
    K32("OpenFileMappingW",       WIN32_API_OpenFileMappingW),
    K32("MapViewOfFile",          WIN32_API_MapViewOfFile),
    K32("UnmapViewOfFile",        WIN32_API_UnmapViewOfFile),
    K32("FlushViewOfFile",        WIN32_API_FlushViewOfFile),
    K32("CopyMemory",             WIN32_API_CopyMemory),
    K32("MoveMemory",             WIN32_API_MoveMemory),
    K32("FillMemory",             WIN32_API_FillMemory),
    K32("ZeroMemory",             WIN32_API_ZeroMemory),

    /* ---------- msvcrt ---------- */
    MCRT("memset",                 WIN32_API_memset),
    MCRT("memcpy",                 WIN32_API_memcpy),
    MCRT("memmove",                WIN32_API_memmove),
    MCRT("memcmp",                 WIN32_API_memcmp),
    MCRT("malloc",                 WIN32_API_malloc),
    MCRT("calloc",                 WIN32_API_calloc),
    MCRT("realloc",                WIN32_API_realloc),
    MCRT("free",                   WIN32_API_free),
    MCRT("strlen",                 WIN32_API_strlen),
    MCRT("strcmp",                 WIN32_API_strcmp),
    MCRT("strncmp",                WIN32_API_strncmp),
    MCRT("strcpy",                 WIN32_API_strcpy),
    MCRT("strncpy",                WIN32_API_strncpy),
    MCRT("strcat",                 WIN32_API_strcat),
    MCRT("strchr",                 WIN32_API_strchr),
    MCRT("strrchr",                WIN32_API_strrchr),
    MCRT("strstr",                 WIN32_API_strstr),
    MCRT("atoi",                   WIN32_API_atoi),
    MCRT("atol",                   WIN32_API_atol),
    MCRT("itoa",                   WIN32_API_itoa),
    MCRT("_itoa",                  WIN32_API__itoa),
    MCRT("_itoa_s",                WIN32_API__itoa_s),
    MCRT("_ltoa",                  WIN32_API__ltoa),
    MCRT("strdup",                 WIN32_API_strdup),
    MCRT("_strdup",                WIN32_API__strdup),
    MCRT("stricmp",                WIN32_API_stricmp),
    MCRT("_stricmp",               WIN32_API__stricmp),
    MCRT("printf",                 WIN32_API_printf),
    MCRT("sprintf",                WIN32_API_sprintf),
    MCRT("snprintf",               WIN32_API_snprintf),
    MCRT("vprintf",                WIN32_API_vprintf),
    MCRT("vsnprintf",              WIN32_API_vsnprintf),
    MCRT("puts",                   WIN32_API_puts),
    MCRT("putchar",                WIN32_API_putchar),
    MCRT("getchar",                WIN32_API_getchar),
    MCRT("fopen",                  WIN32_API_fopen),
    MCRT("fclose",                 WIN32_API_fclose),
    MCRT("fread",                  WIN32_API_fread),
    MCRT("fwrite",                 WIN32_API_fwrite),
    MCRT("fseek",                  WIN32_API_fseek),
    MCRT("ftell",                  WIN32_API_ftell),
    MCRT("fflush",                 WIN32_API_fflush),
    MCRT("_snprintf",              WIN32_API__snprintf),
    MCRT("_vsnprintf",             WIN32_API__vsnprintf),
    MCRT("abort",                  WIN32_API_abort),
    MCRT("exit",                   WIN32_API_exit),
    MCRT("_exit",                  WIN32_API__exit),
    MCRT("getenv",                 WIN32_API_getenv),
    MCRT("system",                 WIN32_API_system),
    MCRT("rand",                   WIN32_API_rand),
    MCRT("srand",                  WIN32_API_srand),
    MCRT("qsort",                  WIN32_API_qsort),
    MCRT("bsearch",                WIN32_API_bsearch),
    MCRT("_beginthreadex",         WIN32_API__beginthreadex),
    MCRT("_endthreadex",           WIN32_API__endthreadex),
    MCRT("time",                   WIN32_API_time),
    MCRT("memchr",                 WIN32_API_memchr),
    MCRT("strncat",                WIN32_API_strncat),
    MCRT("strspn",                 WIN32_API_strspn),
    MCRT("strcspn",                WIN32_API_strcspn),
    MCRT("strpbrk",                WIN32_API_strpbrk),
    MCRT("strtok",                 WIN32_API_strtok),
    MCRT("toupper",                WIN32_API_toupper),

    /* ---------- advapi32 ---------- */
    ADV("RegOpenKeyExA",           WIN32_API_RegOpenKeyExA),
    ADV("RegOpenKeyExW",           WIN32_API_RegOpenKeyExW),
    ADV("RegQueryValueExA",        WIN32_API_RegQueryValueExA),
    ADV("RegQueryValueExW",        WIN32_API_RegQueryValueExW),
    ADV("RegSetValueExA",          WIN32_API_RegSetValueExA),
    ADV("RegSetValueExW",          WIN32_API_RegSetValueExW),
    ADV("RegCloseKey",             WIN32_API_RegCloseKey),
    ADV("RegCreateKeyExA",         WIN32_API_RegCreateKeyExA),
    ADV("RegCreateKeyExW",         WIN32_API_RegCreateKeyExW),
    ADV("RegDeleteKeyA",           WIN32_API_RegDeleteKeyA),
    ADV("RegDeleteKeyW",           WIN32_API_RegDeleteKeyW),
    ADV("RegDeleteValueA",         WIN32_API_RegDeleteValueA),
    ADV("RegDeleteValueW",         WIN32_API_RegDeleteValueW),
    ADV("RegEnumKeyExA",           WIN32_API_RegEnumKeyExA),
    ADV("RegEnumKeyExW",           WIN32_API_RegEnumKeyExW),
    ADV("RegEnumValueA",           WIN32_API_RegEnumValueA),
    ADV("RegEnumValueW",           WIN32_API_RegEnumValueW),
    ADV("RegQueryInfoKeyA",        WIN32_API_RegQueryInfoKeyA),
    ADV("RegQueryInfoKeyW",        WIN32_API_RegQueryInfoKeyW),
    ADV("OpenProcessToken",        WIN32_API_OpenProcessToken),
    ADV("OpenThreadToken",         WIN32_API_OpenThreadToken),
    ADV("LookupPrivilegeValueA",   WIN32_API_LookupPrivilegeValueA),
    ADV("LookupPrivilegeValueW",   WIN32_API_LookupPrivilegeValueW),
    ADV("AdjustTokenPrivileges",   WIN32_API_AdjustTokenPrivileges),
    ADV("GetTokenInformation",     WIN32_API_GetTokenInformation),
    ADV("AllocateAndInitializeSid", WIN32_API_AllocateAndInitializeSid),
    ADV("FreeSid",                 WIN32_API_FreeSid),

    /* ---------- user32 ---------- */
    U32("MessageBoxA",             WIN32_API_MessageBoxA),
    U32("MessageBoxW",             WIN32_API_MessageBoxW),
    U32("CreateWindowExA",         WIN32_API_CreateWindowExA),
    U32("CreateWindowExW",         WIN32_API_CreateWindowExW),
    U32("DefWindowProcA",          WIN32_API_DefWindowProcA),
    U32("DefWindowProcW",          WIN32_API_DefWindowProcW),
    U32("GetMessageA",             WIN32_API_GetMessageA),
    U32("GetMessageW",             WIN32_API_GetMessageW),
    U32("TranslateMessage",        WIN32_API_TranslateMessage),
    U32("DispatchMessageA",        WIN32_API_DispatchMessageA),
    U32("DispatchMessageW",        WIN32_API_DispatchMessageW),
    U32("PostQuitMessage",         WIN32_API_PostQuitMessage),
    U32("ShowWindow",              WIN32_API_ShowWindow),
    U32("UpdateWindow",            WIN32_API_UpdateWindow),
    U32("GetClientRect",           WIN32_API_GetClientRect),
    U32("BeginPaint",              WIN32_API_BeginPaint),
    U32("EndPaint",                WIN32_API_EndPaint),
    U32("LoadIconA",               WIN32_API_LoadIconA),
    U32("LoadIconW",               WIN32_API_LoadIconW),
    U32("LoadCursorA",             WIN32_API_LoadCursorA),
    U32("LoadCursorW",             WIN32_API_LoadCursorW),
    U32("RegisterClassA",          WIN32_API_RegisterClassA),
    U32("RegisterClassW",          WIN32_API_RegisterClassW),
    U32("SetWindowTextA",          WIN32_API_SetWindowTextA),
    U32("SetWindowTextW",          WIN32_API_SetWindowTextW),
    U32("GetWindowTextA",          WIN32_API_GetWindowTextA),
    U32("GetWindowTextW",          WIN32_API_GetWindowTextW),
    U32("GetDesktopWindow",        WIN32_API_GetDesktopWindow),
    U32("GetForegroundWindow",     WIN32_API_GetForegroundWindow),
    U32("SetForegroundWindow",     WIN32_API_SetForegroundWindow),
    U32("FindWindowA",             WIN32_API_FindWindowA),
    U32("FindWindowW",             WIN32_API_FindWindowW),
    U32("SendMessageA",            WIN32_API_SendMessageA),
    U32("SendMessageW",            WIN32_API_SendMessageW),
    U32("PostMessageA",            WIN32_API_PostMessageA),
    U32("PostMessageW",            WIN32_API_PostMessageW),
    U32("RegisterClassExA",        WIN32_API_RegisterClassExA),
    U32("RegisterClassExW",        WIN32_API_RegisterClassExW),
    U32("UnregisterClassA",        WIN32_API_UnregisterClassA),
    U32("UnregisterClassW",        WIN32_API_UnregisterClassW),
    U32("CreateWindowA",           WIN32_API_CreateWindowA),
    U32("CreateWindowW",           WIN32_API_CreateWindowW),
    U32("DestroyWindow",           WIN32_API_DestroyWindow),
    U32("GetParent",               WIN32_API_GetParent),
    U32("SetParent",               WIN32_API_SetParent),
    U32("IsWindow",                WIN32_API_IsWindow),
    U32("IsWindowVisible",         WIN32_API_IsWindowVisible),
    U32("EnableWindow",            WIN32_API_EnableWindow),
    U32("GetSystemMetrics",        WIN32_API_GetSystemMetrics),
    U32("GetWindowRect",           WIN32_API_GetWindowRect),
    U32("MoveWindow",              WIN32_API_MoveWindow),
    U32("SetWindowPos",            WIN32_API_SetWindowPos),
    U32("GetWindowLongA",          WIN32_API_GetWindowLongA),
    U32("SetWindowLongA",          WIN32_API_SetWindowLongA),

    /* ---------- gdi32 ---------- */
    G32("GetStockObject",          WIN32_API_GetStockObject),
    G32("CreateSolidBrush",        WIN32_API_CreateSolidBrush),
    G32("CreatePen",               WIN32_API_CreatePen),
    G32("SelectObject",            WIN32_API_SelectObject),
    G32("DeleteObject",            WIN32_API_DeleteObject),
    G32("TextOutA",                WIN32_API_TextOutA),
    G32("TextOutW",                WIN32_API_TextOutW),
    G32("BitBlt",                  WIN32_API_BitBlt),
    G32("StretchBlt",              WIN32_API_StretchBlt),
    G32("SetBkMode",               WIN32_API_SetBkMode),
    G32("SetTextColor",            WIN32_API_SetTextColor),
    G32("SetBkColor",              WIN32_API_SetBkColor),
    G32("CreateCompatibleDC",      WIN32_API_CreateCompatibleDC),
    G32("CreateCompatibleBitmap",  WIN32_API_CreateCompatibleBitmap),
    G32("DeleteDC",                WIN32_API_DeleteDC),
    G32("GetDeviceCaps",           WIN32_API_GetDeviceCaps),
    G32("Rectangle",               WIN32_API_Rectangle),
    G32("Ellipse",                 WIN32_API_Ellipse),
    G32("MoveToEx",                WIN32_API_MoveToEx),
    G32("LineTo",                  WIN32_API_LineTo),

    /* ---------- shell32 ---------- */
    SH32("ShellExecuteA",          WIN32_API_ShellExecuteA),
    SH32("ShellExecuteW",          WIN32_API_ShellExecuteW),
    SH32("ShellExecuteExA",        WIN32_API_ShellExecuteExA),
    SH32("ShellExecuteExW",        WIN32_API_ShellExecuteExW),
    SH32("SHGetFolderPathA",       WIN32_API_SHGetFolderPathA),
    SH32("SHGetFolderPathW",       WIN32_API_SHGetFolderPathW),
    SH32("SHGetKnownFolderPath",   WIN32_API_SHGetKnownFolderPath),
    SH32("SHGetSpecialFolderPathA", WIN32_API_SHGetSpecialFolderPathA),
    SH32("SHGetSpecialFolderPathW", WIN32_API_SHGetSpecialFolderPathW),

    /* ---------- ole32 ---------- */
    OLE("CoInitialize",            WIN32_API_CoInitialize),
    OLE("CoUninitialize",          WIN32_API_CoUninitialize),
    OLE("CoCreateInstance",        WIN32_API_CoCreateInstance),
    OLE("CoTaskMemAlloc",          WIN32_API_CoTaskMemAlloc),
    OLE("CoTaskMemFree",           WIN32_API_CoTaskMemFree),
    OLE("CoInitializeEx",          WIN32_API_CoInitializeEx),

    /* ---------- ws2_32 ---------- */
    WS2("WSAStartup",              WIN32_API_WSAStartup),
    WS2("WSACleanup",              WIN32_API_WSACleanup),
    WS2("socket",                  WIN32_API_socket),
    WS2("bind",                    WIN32_API_bind),
    WS2("listen",                  WIN32_API_listen),
    WS2("accept",                  WIN32_API_accept),
    WS2("connect",                 WIN32_API_connect),
    WS2("send",                    WIN32_API_send),
    WS2("recv",                    WIN32_API_recv),
    WS2("closesocket",             WIN32_API_closesocket),
    WS2("gethostbyname",           WIN32_API_gethostbyname),
    WS2("getaddrinfo",             WIN32_API_getaddrinfo),
    WS2("freeaddrinfo",            WIN32_API_freeaddrinfo),
    WS2("inet_addr",               WIN32_API_inet_addr),
    WS2("inet_ntoa",               WIN32_API_inet_ntoa),
    WS2("htons",                   WIN32_API_htons),
    WS2("htonl",                   WIN32_API_htonl),
    WS2("ntohs",                   WIN32_API_ntohs),
    WS2("ntohl",                   WIN32_API_ntohl),
    WS2("WSAGetLastError",         WIN32_API_WSAGetLastError),
    WS2("WSASetLastError",         WIN32_API_WSASetLastError),
    WS2("select",                  WIN32_API_select),
    WS2("ioctlsocket",             WIN32_API_ioctlsocket),
    WS2("setsockopt",              WIN32_API_setsockopt),
    WS2("getsockopt",              WIN32_API_getsockopt),
    WS2("shutdown",                WIN32_API_shutdown),
    WS2("recvfrom",                WIN32_API_recvfrom),
    WS2("sendto",                  WIN32_API_sendto),

    /* ---------- winmm ---------- */
    MM("timeGetTime",              WIN32_API_timeGetTime),
    MM("timeBeginPeriod",          WIN32_API_timeBeginPeriod),
    MM("timeEndPeriod",            WIN32_API_timeEndPeriod),
    MM("PlaySoundA",               WIN32_API_PlaySoundA),
    MM("PlaySoundW",               WIN32_API_PlaySoundW),

    /* ---------- comctl32 ---------- */
    CC32("InitCommonControls",     WIN32_API_InitCommonControls),
    CC32("InitCommonControlsEx",   WIN32_API_InitCommonControlsEx),
    CC32("ImageList_Create",       WIN32_API_ImageList_Create),

    /* ---------- ntdll ---------- */
    NTD("NtCreateFile",            WIN32_API_NtCreateFile),
    NTD("NtOpenFile",              WIN32_API_NtOpenFile),
    NTD("NtReadFile",              WIN32_API_NtReadFile),
    NTD("NtWriteFile",             WIN32_API_NtWriteFile),
    NTD("NtClose",                 WIN32_API_NtClose),
    NTD("NtCreateProcess",         WIN32_API_NtCreateProcess),
    NTD("NtCreateThread",          WIN32_API_NtCreateThread),
    NTD("NtAllocateVirtualMemory", WIN32_API_NtAllocateVirtualMemory),
    NTD("NtFreeVirtualMemory",     WIN32_API_NtFreeVirtualMemory),
    NTD("NtQueryInformationProcess", WIN32_API_NtQueryInformationProcess),
    NTD("NtSetInformationProcess", WIN32_API_NtSetInformationProcess),
    NTD("NtQueryInformationThread", WIN32_API_NtQueryInformationThread),
    NTD("NtSetInformationThread",  WIN32_API_NtSetInformationThread),
    NTD("NtWaitForSingleObject",   WIN32_API_NtWaitForSingleObject),
    NTD("NtWaitForMultipleObjects", WIN32_API_NtWaitForMultipleObjects),
    NTD("NtDelayExecution",        WIN32_API_NtDelayExecution),
    NTD("NtQuerySystemInformation", WIN32_API_NtQuerySystemInformation),
    NTD("NtQueryPerformanceCounter", WIN32_API_NtQueryPerformanceCounter),
    NTD("NtQueryVirtualMemory",    WIN32_API_NtQueryVirtualMemory),
    NTD("NtProtectVirtualMemory",  WIN32_API_NtProtectVirtualMemory),
    NTD("NtCreateKey",             WIN32_API_NtCreateKey),
    NTD("NtOpenKey",               WIN32_API_NtOpenKey),
    NTD("NtQueryValueKey",         WIN32_API_NtQueryValueKey),
    NTD("NtSetValueKey",           WIN32_API_NtSetValueKey),
    NTD("NtDeleteKey",             WIN32_API_NtDeleteKey),
    NTD("NtEnumerateKey",          WIN32_API_NtEnumerateKey),
    NTD("NtEnumerateValueKey",     WIN32_API_NtEnumerateValueKey),
    NTD("NtQueryKey",              WIN32_API_NtQueryKey),
    NTD("NtFlushKey",              WIN32_API_NtFlushKey),
    NTD("RtlInitUnicodeString",    WIN32_API_RtlInitUnicodeString),

    /* ---------- userenv ---------- */
    UENV("GetUserProfileDirectoryA", WIN32_API_GetUserProfileDirectoryA),
    UENV("GetUserProfileDirectoryW", WIN32_API_GetUserProfileDirectoryW),
    UENV("GetProfilesDirectoryA",    WIN32_API_GetProfilesDirectoryA),

    /* ---------- kernel32（附加 13 项，补齐 500） ---------- */
    K32X("GetLastError", "GetLastError_Compat", WIN32_API_GetLastError_Compat),
    K32("SetConsoleTitleA",        WIN32_API_SetConsoleTitleA),
    K32("GetConsoleTitleA",        WIN32_API_GetConsoleTitleA),
    K32("SetConsoleWindowSize",    WIN32_API_SetConsoleWindowSize),
    K32("GetCurrentConsoleFont",   WIN32_API_GetCurrentConsoleFont),
    K32("GetProcessVersion",       WIN32_API_GetProcessVersion),
    K32("GetProcessAffinityMask",  WIN32_API_GetProcessAffinityMask),
    K32("SetThreadAffinityMask",   WIN32_API_SetThreadAffinityMask),
    K32("SwitchToThread",          WIN32_API_SwitchToThread),
    K32("GetThreadContext",        WIN32_API_GetThreadContext),
    K32("SetThreadContext",        WIN32_API_SetThreadContext),
    K32("FlushInstructionCache",   WIN32_API_FlushInstructionCache),
    K32("GetCurrentProcessorNumber", WIN32_API_GetCurrentProcessorNumber),
};

const uint32_t g_win32_api_table_count =
    (uint32_t)(sizeof(g_win32_api_table) / sizeof(g_win32_api_table[0]));

uint32_t win32_api_table_count(void)
{
    return g_win32_api_table_count;
}

#undef K32
#undef K32X
#undef MCRT
#undef ADV
#undef U32
#undef G32
#undef SH32
#undef OLE
#undef WS2
#undef MM
#undef CC32
#undef NTD
#undef UENV
/*===OmniBridgeOs/kernel/arch/x64/user/win32_api_table.c 结束===*/