#!/usr/bin/env python3
#===OmniBridgeOs/scripts/obr_to_c.py===
"""
把 .obr 二进制转为 C 数组，供内核内嵌。

用法：
    obr_to_c.py <input.obr> <output.c> <sym_suffix>

生成：
    const uint8_t  g_embedded_<sym_suffix>[];
    const uint64_t g_embedded_<sym_suffix>_len;
"""
import sys
import os

def main():
    if len(sys.argv) != 4:
        print("usage: obr_to_c.py <input.obr> <output.c> <sym_suffix>",
              file=sys.stderr)
        sys.exit(1)

    in_path, out_path, sym = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path, "rb") as f:
        data = f.read()
    if len(data) == 0:
        print(f"[obr_to_c] ERROR: {in_path} is empty", file=sys.stderr)
        sys.exit(1)

    with open(out_path, "w") as f:
        f.write("/* Auto-generated by scripts/obr_to_c.py. Do not edit. */\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint8_t g_embedded_{sym}[] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk)
                    + ",\n")
        f.write("};\n\n")
        f.write(f"const uint64_t g_embedded_{sym}_len = {len(data)}ull;\n")

    print(f"[obr_to_c] {in_path} ({len(data)} bytes) -> {out_path} "
          f"(sym=g_embedded_{sym})")

if __name__ == "__main__":
    main()
#===OmniBridgeOs/scripts/obr_to_c.py 结束===